/* do not change this file, it is auto generated by storybook. */
import '@storybook/addon-ondevice-actions/register';
import '@storybook/addon-ondevice-controls/register';
import { start, updateView } from '@storybook/react-native';

const normalizedStories = [
  {
    titlePrefix: '',
    directory: '../../packages/ui/src',
    files: '**/*.stories.@(ts|tsx)',
    importPathMatcher:
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(ts|tsx))$/,
    req: require.context(
      '../../../packages/ui/src',
      true,
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(ts|tsx))$/
    ),
  },
  {
    titlePrefix: '',
    directory: './components',
    files: '**/*.stories.@(ts|tsx)',
    importPathMatcher:
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(ts|tsx))$/,
    req: require.context(
      '../components',
      true,
      /^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(ts|tsx))$/
    ),
  },
];

declare global {
  var view: ReturnType<typeof start>;
  var STORIES: typeof normalizedStories;
  interface NodeModule {
    hot?: {
      accept?: () => void;
    };
  }
}

const annotations = [
  require('./preview'),
  require('@storybook/react-native/preview'),
  require('@storybook/addon-ondevice-actions/preview'),
];

global.STORIES = normalizedStories;

module?.hot?.accept?.();

if (!global.view) {
  global.view = start({
    annotations,
    storyEntries: normalizedStories,
  });
} else {
  updateView(global.view, annotations, normalizedStories);
}

export const view = global.view;
